# Generated by Django 3.2.7 on 2021-09-26 22:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=100)),
                ('first_last_name', models.CharField(max_length=100)),
                ('second_last_name', models.CharField(max_length=100, null=True)),
                ('identity_document_number', models.IntegerField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FAMALE')], default='M', max_length=1)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('employed_number', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('boss', models.IntegerField()),
                ('zone', models.CharField(max_length=100)),
                ('municipe', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('sells', models.IntegerField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('cell_phone', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'CustomUser',
            },
        ),
    ]
